### ISSUE TITLE
 in de title staat  %s - undefined

### ISSUE THREAD

**Issue by rubenclaes** [rubenclaes/de-verenigde-vrienden-nuxt-strapi#8]

**Comment by jorisclaes** [comment]
is dit een goede oplossing
ik kon niet direct iets beter vinden in de docs

in de .env file
`APP_ID=Koninklijke Harmonie De Verenigde Vrienden Heusden-Zolder`

en in pages index
```
head () {
    return {
      title: "Homepage - " + process.env.APP_ID
    }
}
```

**Comment by rubenclaes** [comment]
> is dit een goede oplossing
> ik kon niet direct iets beter vinden in de docs
> 
> in de .env file
> `APP_ID=Koninklijke Harmonie De Verenigde Vrienden Heusden-Zolder`
> 
> en in pages index
> 
> ```
> head () {
>     return {
>       title: "Homepage - " + process.env.APP_ID
>     }
> }
> ```

Ik heb het aangepast zodat het nu dynamisch per pagina wordt opgehaald. Merci!
